package com.myspace.randomproject123;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class demoobj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer empId;

	public demoobj() {
	}

	public java.lang.Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(java.lang.Integer empId) {
		this.empId = empId;
	}

	public demoobj(java.lang.Integer empId) {
		this.empId = empId;
	}

}