package com.myspace.randomproject123;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class demoobj implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public demoobj() {
    }




}